### PR TITLE
Add fix for encoding problems

### PR DESCRIPTION
**Pull request by kreyssel**
We had some issues with german umlauts in encoded passwords.

I'm looking into PBECipher and found that he use not always string encoding.

Hope you can this add to maven core too.

### CODE REVIEW

**Comment by bentmann** [comment]
Good catch, thanks! But before merging this in, could you fix the following minor things:
- Use 2-spaces as intend in the POM, i.e. basically use the existing formatting
- Use UTF-8 or maybe Unicode escapes for the umlauts in the tests? Right now, the file appears to be using Latin-1 whereas the sources are (meant to be) encoded in UTF-8.

**Comment by kreyssel** [comment]
Ok, switched to 2 spaces for POM.

Can you recheck encoding of PBECipherTest.java? I think that i have switched encoding in commit [12de44c](https://github.com/kreyssel/plexus-cipher/commit/12de44ca117722e0c9bee11dd14c38d2c17a4d34) - take a look at wrong encoding in first commit [6ccec0e](https://github.com/kreyssel/plexus-cipher/commit/6ccec0eaefb9844d3cb83e57bdc155ec16f2e6c0).

**Comment by kreyssel** [comment]
Added issue for maven to include it in a new release.

http://jira.codehaus.org/browse/MNG-5131

**Comment by bentmann** [comment]
Merged, thank you!

**Pull request closed without merging**
